import type { Metadata } from "next";
// Import the global styles
import "./globals.css";
// Import the fonts
import { roboto } from "../ui/Fonts";
// Import the app
import App from "./App";

// Set the metadata for the page
export const metadata: Metadata = {
  title: "The House of Wisdom",
  description: "Generated by The House of Wisdom Team",
};

// Create the layout for the page
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <App>{children}</App>
      </body>
    </html>
  );
}
